In [ ]:
import os
import sys

sys.path.append("/data/zhangyufeng/Rec/dl-based")

In [10]:
from models import PNN

In [ ]:
pnn = PNN()

models.PNN.PNN

In [19]:
import torch

In [34]:
# 创建示例数据
vector = torch.tensor([[1], [2], [3]])
matrix = torch.tensor([[1, 2, 3, 1], [4, 5, 6, 1], [7, 8, 9, 1]])

vector, matrix

(tensor([[1],
         [2],
         [3]]),
 tensor([[1, 2, 3, 1],
         [4, 5, 6, 1],
         [7, 8, 9, 1]]))

In [39]:
torch.outer(vector.reshape(-1), vector.reshape(-1))

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [ ]:
vector.reshape(-1, 1)

tensor([1, 2, 3])